### ISSUE TITLE
Authentication error on export, no oAuth support?

### ISSUE THREAD

**Issue by corpulent** [expressodev/cx_disqus#1]
Hi,  I get an authentication error when I try to export comments to DISQUS.

```
An Error Was Encountered
There was an error exporting your comments! The following details may be helpful:

Error 4: You must be authenticated to perform this action
```

I think DISQUS uses oAuth now, and this plugin does not, so it does not work at all it seems.

**Comment by amacneil** [comment]
Actually that error often happens when a comment doesn't have an email
address associated with it. Did you already set up your disqus application
before they started forcing Oauth? Is there a comment mentioned below that
error?
