### ISSUE TITLE
oAuth is the only option now

### ISSUE THREAD

**Issue by ossgeek314** [expressodev/cx_disqus#2]
It appears that oAuth is the default and only option for authentication on disqus api applications now.  I am just now signing up for disqus so I guess I'm not able to utilize the old method.

Are there plans to integreate oAuth into cx_disqus in the future?

**Comment by amacneil** [comment]
Yes, unfortunately Disqus do not allow you to use the old authentication method for new accounts, and we do not have the resources to completely rewrite this plugin to support OAuth. Hence we have open sourced it in the hopes that someone from the community might take on updating it, or use it as the basis for their own Disqus plugin.
